- persistent/internal/driver/mgo/lyfe_cycle_test.go
- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/persistent_storage.go
Changed `UpdateMany` for `BulkUpdate` since it was working for updating multiple rows with multiple queries.
Created `UpdateAll`, which receives two queries - one for filtering and the other for applying changes.
An example of UpdateAll would be - 
before:
```go
p := Policy{}
col := MainStorage.(*Mongo).session.DB("").C(p.TableName())
updateQuery := bson.M{"$unset": bson.M{fmt.Sprintf("access_rights.%s", apiID): ""}}
_, err := col.UpdateAll(nil, updateQuery)
```
Now
```go
updateQuery:= dbm.DBM{"$unset":dbm.DBM{fmt.Sprintf("access_rights.%s", apiID): ""}}
filterQuery := dbm.DBM{}
err := storage.UpdateAll(context.Background(),  &Policy{}, filterQuery, updateQuery}
```
This allows to more complex UpdateAll scenarios, for example if we want to increment by 20 the `license.limit` field of all …
> TT-8286 Mongo drivers UpdateAll and BulkUpdate

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/errors.go
- persistent/internal/model/persistent_storage.go
https://tyktech.atlassian.net/browse/TT-8289
> TT-8289 Feat/count with filters

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mgo/migrations.go
- persistent/internal/driver/mgo/migrations_test.go
- persistent/internal/driver/mongo/migrations.go
- persistent/internal/driver/mongo/migrations_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/errors.go
AutoMigrate functions were created for both Mongo Drivers.
https://tyktech.atlassian.net/browse/TT-8162?atlOrigin=eyJpIjoiNTBmOTcyNDA2YjRiNDFmYWFmYmQxNWE0MTQ5MTcwNTEiLCJwIjoiaiJ9
> [TT-8162] - AutoMigrate function for both Mongo drivers

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/persistent_storage.go
Adding AutoMigrate to persistent storage interface - modifying mgo function signature
> Adding AutoMigrate to persistent storage interface

- persistent/id/object_id.go
- persistent/id/object_id_test.go
Added the required methods so SQL engines can work with this ID
> Add methods to objectID to work with SQL

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/persistent_storage.go
https://tyktech.atlassian.net/browse/TT-8329?atlOrigin=eyJpIjoiYzZlZjk2OWRmZjA2NDZlZTgyNDU2NmUyZjk3MjFiZTUiLCJwIjoiaiJ9
> TT-8329 Aggregate function to mgo and mongo drivers

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/persistent_storage.go
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-8387
> TT-8387 DBTableStats to Mongo and mgo drivers

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/persistent_storage.go
https://tyktech.atlassian.net/browse/TT-8401?atlOrigin=eyJpIjoiMTQ5NGQ4NWVlMDhiNGQ3OTg5YzFhNTA4MDBjZjRmMjciLCJwIjoiaiJ9
> [TT-8401] Implementing CleanIndexes function

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/persistent_storage.go
https://tyktech.atlassian.net/browse/TT-8488?atlOrigin=eyJpIjoiMjFhYjNjZDJlY2FiNDkxNWE4MjJhMzU4ZjVjYWQ3ZmQiLCJwIjoiaiJ9
> [TT-8488] Implementing Upsert function

- persistent/id/object_id.go
- persistent/id/object_id_test.go
Implement a method to generate object Ids given a date, so users can perform filters based on the timestamp of the id
https://tyktech.atlassian.net/browse/TT-8523
Unblock integration
- Added unit test
> implemented the newobjectIDwithTime method

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/mongo.go
- persistent/internal/driver/mongo/mongo_test.go
- persistent/internal/model/errors.go
Now we are returning an error if we want to get the indexes of a not created collection
> Indexes: returning error if collection does not exist

- persistent/internal/driver/mgo/mgo_test.go
- persistent/internal/driver/mongo/migrations.go
- persistent/internal/driver/mongo/migrations_test.go
- persistent/internal/driver/mongo/mongo_test.go
> changing key values in buildOpt function

- persistent/internal/driver/mgo/mgo.go
- persistent/internal/driver/mongo/mongo.go
Adding handleStoreError checker on every method to check if the returned error of a function is related to the database connection.
> Adding handleStoreError checker on every method

- persistent/model/object_id.go
- persistent/model/object_id_test.go
In order to maintain backward compatibility with gateway apidef objectId, we add a new wrapper func for `Time` and change the `String` func to return the `Hex`
> ObjectID backward compatible Time and String

- persistent/internal/driver/mgo/life_cycle.go
- persistent/internal/driver/mongo/life_cycle.go
- persistent/internal/driver/mongo/life_cycle_test.go
- persistent/internal/types/client_options.go
Adding `DirectConnection` option to `ClientOpts`:
DirectConnection informs whether to establish connections only with the specified seed servers or to obtain information for the whole cluster and establish connections with further servers too. If true, the client will only connect to the host provided in the ConnectionString and won't attempt to discover other hosts in the cluster. Useful when network restrictions prevent discovery, such as with SSH tunneling. Default is false.
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-8873
> [TT-8873] Adding DirectConnection to ClientOpts

- persistent/internal/helper/functions.go
- persistent/internal/helper/functions_test.go
There was a bug with connection strings that were using +srv. This function was removing that part of the URI. Now, unit tests with that type of connection string were added.
https://tyktech.atlassian.net/browse/TT-8971?atlOrigin=eyJpIjoiOWZlYTI1ZWFiYTQ5NDFhODliZDczNTZlZDE1MTYxYjkiLCJwIjoiaiJ9
> [TT-8971] Fixing connection strings with +srv bug

- persistent/internal/driver/mgo/life_cycle.go
- persistent/internal/driver/mongo/life_cycle.go
- persistent/internal/helper/functions.go
- persistent/internal/helper/functions_test.go
With the new password encoding method, there's a bug in CosmosDB URLs that we're using in QA since they have more than one '@' character. This has been fixed by just getting the last '@' before the ':' delimiter, omitting those who are after the port in the connection string. 
If the connection string doesn't have any port, we'll just take the last '@'. In this case, if the user has multiple '@' in their connection string, it would be recommended to set the password manually encoded by itself.
https://tyktech.atlassian.net/browse/TT-8978?atlOrigin=eyJpIjoiY2Q2OTUxNDYxNWFhNDk3NGI2ODVhYmQ4OTk3MDg2NDciLCJwIjoiaiJ9
> [TT-8978] Fixing CosmosDB URL bug

- persistent/internal/driver/mgo/query.go
- persistent/internal/driver/mongo/query.go
We're now checking if an `_id` is a valid ObjectID to prevent panics.
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-9116
> [TT-9116] Safe checking if string is a valid ObjectID

- persistent/internal/driver/mgo/query.go
- persistent/internal/driver/mgo/query_test.go
- persistent/internal/driver/mongo/query.go
- persistent/internal/driver/mongo/query_test.go
When using nested queries, only a single key has been considered while building the query. 
This PR fixes it. 
Previously 
```
model.DBM{
"value": model.DBM{
"$gte": 0,
"$lte": 10
},
}
```
got translated to 
```
bson.M{
"value": bson.M{
"$gte": 0
},
}
```
or 
```
bson.M{
"value": bson.M{
"$lte": 10
},
}
```
This PR fixes it to be
```
bson.M{
"value": bson.M{
"$gte": 0,
"$lte": 10
},
}
```
https://tyktech.atlassian.net/browse/TT-9704
> [TT-9704] fix a bug where only a single key from nested query is considered.

- README.md
> Update Roadmap on README.md

- persistent/internal/driver/mongo/mongo.go
Deferring cursor closure only if no error is present. This is causing panics since we're trying to close a cursor that wasn't initialized.
https://tyktech.atlassian.net/browse/TT-10479
https://tyktech.atlassian.net/browse/TT-10479
> [TT-10479] Deferring cursor closure only if no error is present

- temporal/flusher/flsher_test.go
- temporal/internal/driver/redisv8/sortedset.go
- temporal/internal/testutil/testutil.go
- temporal/keyvalue/keyvalue_test.go
- temporal/list/list_test.go
- temporal/model/types.go
- temporal/sortedset/sortedset.go
- temporal/sortedset/sortedset_test.go
Creating SortedSet interface and its Redis v8 implementation.
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?selectedIssue=TT-10390
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?selectedIssue=TT-10390
> [TT-10930] SortedSet interface

- temporal/connector/connector_test.go
- temporal/internal/driver/redisv8/reconnector.go
- temporal/internal/driver/redisv8/redisv8.go
- temporal/model/config.go
- temporal/model/options.go
- temporal/model/options_test.go
- temporal/model/types.go
https://tyktech.atlassian.net/browse/TT-10519
> TT-10519 Temporal Options: WithRetries and WithOnConnect

- temporal/internal/driver/redisv9/keyvalue.go
- temporal/keyvalue/keyvalue_test.go
This PR fixes TTL return value when the key doesn't exist or doesn't have TTL set.
In Redis 2.6 or older the command returns -1 if the key does not exist or if the key exist but has no associated expire.
Starting with Redis 2.8 the return value in case of error changed:
The command returns -2 if the key does not exist.
The command returns -1 if the key exists but has no associated expire
> Fix KeyValue TTL

- .github/workflows/ci-tests.yml
Upgrading download-artifact and upload-artifact to fix CIs
> Upgrading download-artifact and upload-artifact to fix CIs
